version: '3'
services:
  sonarscanner:
    image: library/sonarqube
    networks:
        - sonar-network
    ports:
        - "9000:9000"
        - "9092:9092"
    environment:
        - SONARQUBE_JDBC_USERNAME=sonar
        - SONARQUBE_JDBC_PASSWORD=sonar
        - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes: 
        - sonarqube-conf:/opt/sonarqube/conf
        - sonarqube-data:/opt/sonarqube/data
        - sonarqube-extensions:/opt/sonarqube/extensions
        - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    restart: always
    depends_on:
        - postgres
  postgres:
    image: postgres
    networks:
        - sonar-network
    environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
    volumes:
        - postgresql:/var/lib/postgresql
        - postgresql-data:/var/lib/postgresql/data
    restart: always
volumes:
    sonarqube-conf:
    sonarqube-data:
    sonarqube-extensions:
    sonarqube-bundled-plugins:
    postgresql:
    postgresql-data:
networks:
    sonar-network:
        driver: bridge